### ISSUE TITLE
Mistakes in .gitignore

### ISSUE THREAD

**Issue by bartoll** [yireo-training/magento2-gitignore#1]
Hi,
I found some mistakes in your .gitignore file

1. Patterns that are overridden by further pattern
<pre>
/pub/media/*.*
!/pub/media/.htaccess
...
.htaccess
</pre>

2. Trying to re-include files that are in excluded folder
<pre>
dev/
!dev/tools/grunt/configs/themes.js
</pre>

"An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. " (https://git-scm.com/docs/gitignore)

**Comment by jissereitsma** [comment]
Thanks. This was indeed overlooked. You addressed the issues as if there were some general issues with the examples you mentioned only being examples. However, apart from the 2 issues you found, I don't see other issues. Those issues are now fixed. I used the command `git check-ignore -v x` to browse through some of the files and the ignore file seems correct now. Thanks for the thorough report and sorry for the delay.
